/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './ui/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#00dbe8',
        'secondary-container': '#e2dfde',
        'outline': '#7e775f',
        'secondary-fixed': '#e5e2e1',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#1c1b1b',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#79f5ff',
        'on-secondary-container': '#636262',
        'surface-container': '#eeeeee',
        'on-error-container': '#93000a',
        'surface-tint': '#705d00',
        'on-tertiary-fixed': '#002022',
        'on-tertiary-container': '#006a70',
        'surface': '#f9f9f9',
        'secondary': '#5f5e5e',
        'surface-variant': '#e2e2e2',
        'on-secondary': '#ffffff',
        'inverse-primary': '#e9c400',
        'surface-container-high': '#e8e8e8',
        'secondary-fixed-dim': '#c8c6c5',
        'inverse-surface': '#2f3131',
        'error-container': '#ffdad6',
        'primary-container': '#ffd700',
        'on-background': '#1a1c1c',
        'primary': '#705d00',
        'surface-container-low': '#f3f3f3',
        'on-primary-fixed': '#221b00',
        'surface-container-highest': '#e2e2e2',
        'surface-dim': '#dadada',
        'on-primary-container': '#705e00',
        'on-tertiary-fixed-variant': '#004f54',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f9f9f9',
        'tertiary-container': '#00f1ff',
        'on-primary-fixed-variant': '#544600',
        'tertiary': '#00696f',
        'inverse-on-surface': '#f1f1f1',
        'primary-fixed': '#ffe16d',
        'background': '#f9f9f9',
        'on-secondary-fixed-variant': '#474746',
        'primary-fixed-dim': '#e9c400',
        'outline-variant': '#d0c6ab',
        'on-error': '#ffffff',
        'on-surface-variant': '#4d4732',
        'error': '#ba1a1a',
        'on-surface': '#1a1c1c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'sm': '8px',
        'md': '16px',
        'xl': '40px',
        'container-max': '800px',
        'lg': '24px',
        'base': '4px',
        'xs': '4px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'mono': ['JetBrains Mono'],
        'body-lg': ['Inter'],
        'headline-sm': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'mono': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
